'''
Title:AI Detector
Date:2025-11-30
Source: https://www.freecodecamp.org/learn/daily-coding-challenge/2025-11-30
Description:
Given a string of one or more sentences, determine if it was likely generated by AI using the following rules:

It contains two or more dashes (-).

It contains two or more sets of parenthesis (()). Text can be within the parenthesis.

It contains three or more words with 7 or more letters.

Words are separated by a single space and only consist of letters (A-Z). Don't include punctuation or other non-letters as part of a word.

If the given sentence meets any of the rules above, return "AI", otherwise, return "Human".

Examples:
Waiting:1. detect_ai("The quick brown fox jumped over the lazy dog.") should return "Human".
Waiting:2. detect_ai("The hypersonic brown fox - jumped (over) the lazy dog.") should return "Human".
Waiting:3. detect_ai("Yes - you're right! I made a mistake there - let me try again.") should return "AI".
Waiting:4. detect_ai("The extraordinary students were studying vivaciously.") should return "AI".
Waiting:5. detect_ai("The (excited) student was (coding) in the library.") should return "AI".
'''
def detect_ai(text):
    count_dash = text.count('-')
    count_parentheses = text.count('(')
    if count_dash >= 2:
        return "AI"
    if count_parentheses >= 2:
        return  "AI"
    
    clean = ""
    for char in text:
        if char.isalpha():
            clean += char
        else:
            clean += " "
    words = clean.split()
    long_word = sum(1 for word in words if len(word) >= 7)
    if long_word >= 3:
        return "AI"

    return "Human"

print(detect_ai("The quick brown fox jumped over the lazy dog."))  # Human
print(detect_ai("The hypersonic brown fox - jumped (over) the lazy dog."))  # Human
print(detect_ai("Yes - you're right! I made a mistake there - let me try again."))  # AI
print(detect_ai("The extraordinary students were studying vivaciously."))  # AI
print(detect_ai("The (excited) student was (coding) in the library."))  # AI
